apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app1
                operator: In
                values: 
                   - new   
          preferedDuringSchedulingIgnoredDuringExecution:
          - weight: 3
            preference:
              matchExpressions:
              - key: app
                operator: In
                values:
                  - fix
          - weight: 4
            preference: 
              matchExpressions:
               - key: disktype
                 operator: In 
                 values: 
                   - ssd
      containers:
        - name: nginx-cont
          image: nginx
          ports:
            - containerPort: 80
      nodeSelector:
         disktype: ssd 
      tolerations:
        - key: "app2"
          operator: "Key2"
          effect: "PreferNoSchedule"
        - key: "app3"
          operator: "Exists"
          effect: "NoExecute"
        # - key: "new2"
        #   value: "value2"
        #   operator: "Equal"
        #   effect: "NoExecute"
        