apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec: 
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
    affinity:
      nodeAffinity:
         requiredDuringSchedulingIgnoredExecution:
           nodeSelectorTerms:
            - matchExpressions:
               - key: 
      containers:
        - name: nginx-cont
          image: nginx
          volumeMounts:
            - mountPath: /usr/share/nginx/www
              name: nginx-vol
      volumes:
        - name: nginx-vol
          persistentVolumeClaim:
            claimName: pvc-new 
      tolerations:
        - key: "new"
          operator: "Equal"
          value: "Value1"
          effect: "NoSchedule"