apiVersion: v1
kind: PersistentVolume
metadata: 
 name: new-vol-1
spec:
 capacity:
  storage: 4Gi
 accessModes: 
   - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 storageClassName: standard
 volumeMode: Filesystem
 hostPath:
  path: /tmp