apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels: 
    app: nginx-app-rs
spec:
  replicas: 4
  selector:
    matchLabels: 
      app: nginx-app-rs
  template:
    metadata: 
      labels:
        app: nginx-app-rs
    spec:
      containers: 
        - name: nginx
          image: nginx