apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-application
  namespace: argocd
spec:
  destination:
     namespace: nginx-name
     server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: nginx-name
    repoURL: "https://github.com/amitmaurya0712/argocd-project/tree/main/argocd%20projects"
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true