apiVersion: v1
kind: Secret
metadata:
  name: private-repo-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/amitmaurya0712/argocd-project.git
  password: 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
  username: amitmaurya07
