apiVersion: apps/v1
kind: Deployment
metadata: 
 name: nginx-deploy
spec: 
  selector:
    matchLabels:
      app: nginx-app
  replicas: 3
  template:
    metadata: 
      labels: 
        app: nginx-app
    spec:
      containers:
          - name: nginx-cont
            image: nginx
            ports:
             - containerPort: 80
            volumeMounts:
              - mountPath: "/usr/share/nginx/html"
                name: nginx-vol
      volumes:
      - name: nginx-vol
        persistentVolumeClaim:
          claimName: pvc-vol
     